version: '3.3'
services:
    work-trial-interface:
        container_name: sample-clean-architecture-react-app
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 3002:3002
